### ISSUE TITLE
Sensitive box

### ISSUE THREAD

**Issue by ghost** [FChannel0/Server#78]
"Mark sensitive" checkbox has no effect on my board. It posts the pic as it usually does. Just passing along info to see if others
are experiencing this- in my case it does not matter as I like to remove the "Mark sensitive" checkbox anyway. 

edit/// Exact same behavior on other boards by the way... the checkbox has no effect (using the tor browser and version 1.1 of Fchan on 3 sites tested so far- mine, and 2 other sites)

edit1-  The title ... lol. 

edit 2/// why does this repo readme still point to fchan.xyz, a broken link? That is kinda autistic. I volunteer to run and maintain a clean demo board if the owner wants... let me know. I can run it long term. I could make it into something funny, like a cult board to thank the lead dev or something. While I do not judge others and believe in anti-censorship, I am quite sure that someone new to fchan and who has never seen a fchan board before might not find the best demo in toilet paper chan and boards that are far worse in name and content. THis repo is a dam nice app-, if you want a more civilized decent demo board let me know. It would serve fchan dev much better to showcase a neutral, non-controversial board. Of course, people realize that chans branch out to all sorts of different creative themes... but as it stands now, there is no neutral demo board for people to see what fchan is.

**Comment by textboards** [comment]
Exact same behavior on other boards by the way... the checkbox has no effect
